---

name: python check

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: Style check
        run: |
          pipenv run black --check
      - name: Dep Security Check
        run: |
          pipenv check

